### ISSUE TITLE
protoc-gen-bufmonkey location

### ISSUE THREAD

**Issue by mazefest** [chesapeaketechnology/BufMonkey#5]
"Download protoc-gen-bufmonkey and extract the files into the same" where can I find the protoc-gen-bufmonkey, referenced in the ReadMe?

Thanks

**Comment by kaedenbrinkman** [comment]
I was able to get this to work. Open the project and run the Grandle task `createAllExecutables`. Then you should be able to find `protoc-gen-bufmonkey` in `/generator/build/artifacts/`.

I then renamed the executable to `protoc-gen-bufmonkey.exe` and moved it to a folder in my `$PATH`.

Finally, I generated my files using `protoc .\my_proto_file.proto --bufmonkey_out=./my_output_dir`
